# Generated by Django 5.0.3 on 2024-04-02 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('type_User', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='soutenanceApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='soutenanceApp.utilisateur')),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bloc', models.IntegerField()),
                ('num_salle', models.IntegerField()),
                ('idAdministrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation_salle',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('date_occupation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('idSalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.salle')),
                ('idAdministrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Domain_expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('idAdministrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50, unique=True)),
                ('domaine', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation_Enseignant',
            fields=[
                ('ide', models.AutoField(primary_key=True, serialize=False)),
                ('date_occupation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='EnseignantDomaineExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDomaineExpertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.domain_expertise')),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='soutenanceApp.utilisateur')),
                ('nom_binom', models.CharField(max_length=50)),
                ('prenom_binom', models.CharField(max_length=50)),
                ('annee_etude', models.CharField(max_length=50)),
                ('memoire', models.BinaryField()),
                ('domain', models.CharField(max_length=50)),
                ('etat_memoire', models.CharField(max_length=50)),
                ('remarque_memoire', models.CharField(max_length=255)),
                ('idEnseignantEncadrant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.enseignant')),
                ('idTheme', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('role_enseignant', models.CharField(max_length=50)),
                ('idSalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.salle')),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.enseignant')),
                ('idLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.leader')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=50)),
                ('idTheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.theme')),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.enseignant')),
                ('idLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenanceApp.leader')),
            ],
        ),
    ]
