from django.urls import path
from soutenanceApp import views
# de views c'est la fonctions ,
urlpatterns=[
    path('',views.renderIndex,name="index"),
    path('login/',views.login,name="dashBoard"),
    path('utilisateur/',views.renderUtilisateur,name="utilisateur"),
    path('utilisateur/ajoutUtilisateur/',views.ajoutUtilisateur,name="ajoutUtilisateur"),
    path('utilisateur/rechercheUtilisateur/',views.renderUtilisateur,name="rechercheUtilisateur"),
    path('utilisateur/rechercheUtilisateur/modifierUtilisateur/<str:email>/',views.rendermodifierUtilisateur,name="affichmodifUtilisateur1"),
    path('utilisateur/rechercheUtilisateur/modifierUtilisateur/<str:email>/MAJUtilisateur/',views.MAJUtilisateur,name="MAJUtilisateur1"),
    path('utilisateur/rechercheUtilisateur/suprimerUtilisateur/<str:email>/',views.suprimerUtilisateur,name="suprimerUtilisateur1"),
    path('utilisateur/suprimerUtilisateur/<str:email>/',views.suprimerUtilisateur,name="suprimerUtilisateur"),
    path('utilisateur/modifierUtilisateur/<str:email>/',views.rendermodifierUtilisateur,name="affichmodifUtilisateur"),
    path('utilisateur/modifierUtilisateur/<str:email>/MAJUtilisateur/',views.MAJUtilisateur,name="MAJUtilisateur"),
    path('salles/',views.renderSalles,name="salles"),
    path('configuration/',views.renderConfiguration,name="configuration"),
    path('planning/',views.renderPlanning,name="planning"),
    path('themes/',views.renderThemes,name="themes"),
    path('infoPersonnel/',views.renderInfoPersonnel,name="infoPersonnel"),
    path('demandes/',views.renderDemandes,name="demandes"),
    path('evaluation/',views.renderEvaluation,name="evaluation"),
    path('demanderthemes/',views.renderDemanderThemes,name="demanderthemes"),
    path('deposerMemoire/',views.renderDeposerMemoire,name="deposerMemoire"),
]